window.__pw={v:5,jobs:{},CH:240000,KEEP:new Set(['used','graded','manual-only']),
sleep:ms=>new Promise(r=>setTimeout(r,ms)),
txt:el=>el?el.textContent.replace(/\s+/g,' ').trim():'',
money:s=>{const m=String(s||'').match(/\$\s*([\d,]+(?:\.\d{1,2})?)/);return m?Number(m[1].replace(/,/g,'')):null;},
async get(url,init){for(let a=0;a<4;a++){let r;try{r=await fetch(url,init);}catch(e){await this.sleep(4000*(a+1));continue;}if(r.status===429||r.status>=500){await this.sleep(8000*(a+1));continue;}return {status:r.status,url:r.url,html:r.ok?await r.text():''};}return {status:-1,url,html:''};},
parseCard(res){if(!res.html)return {status:res.status,finalUrl:res.url};const d=new DOMParser().parseFromString(res.html,'text/html'),h=res.html,h1=d.querySelector('#product_name');const guide={};for(const id of ['used_price','complete_price','new_price','graded_price','box_only_price','manual_only_price']){const v=this.money(this.txt(d.querySelector('#'+id)));if(v!=null)guide[id]=v;}
 let chart=null;try{const m=h.match(/VGPC\.chart_data\s*=\s*(\{[\s\S]*?\});/);if(m){const cd=JSON.parse(m[1]);chart={};for(const k of ['used','graded','manualonly'])if(cd[k])chart[k]=cd[k].filter(p=>p[1]>0).map(p=>[new Date(p[0]).toISOString().slice(0,7),p[1]]);}}catch(e){}
 let pop=null;try{const m=h.match(/VGPC\.pop_data\s*=\s*(\{[\s\S]*?\}|null);/);if(m)pop=JSON.parse(m[1]);}catch(e){}
 const rows=[];for(const div of d.querySelectorAll('div[class^="completed-auctions-"]')){const section=div.className.replace(/^completed-auctions-/,'').split(' ')[0];if(!this.KEEP.has(section))continue;for(const tr of div.querySelectorAll('tbody tr')){const a=tr.querySelector('td.title a');const date=this.txt(tr.querySelector('td.date'));if(!a||!/^\d{4}-\d{2}-\d{2}$/.test(date))continue;const price=this.money(this.txt(tr.querySelector('td.numeric:not(.listed-price) .js-price')||tr.querySelector('td.numeric')));const listed=this.money(this.txt(tr.querySelector('td.listed-price')));const href=a.getAttribute('href')||'';const em=href.match(/ebay\.[a-z.]+\/itm\/(\d+)/i);rows.push([section,date,price,listed,tr.id||'',this.txt(a),em?('ebay:'+em[1]):href.replace(/\?.*$/,'').slice(0,160)]);}}
 return {status:res.status,finalUrl:res.url,name:this.txt(h1).slice(0,140),productId:h1?.getAttribute('title')||null,console:h1?.querySelector('a')?.getAttribute('href')||null,guide,chart,pop,rows};},
start(tag,fn){const job={tag,state:'running',started:Date.now(),progress:0};this.jobs[tag]=job;job.promise=fn(job).then(d=>{job.data=d;job.state='done';}).catch(e=>{job.error=String(e);job.state='error';});return tag+' started';},
async gz(str){const cs=new CompressionStream('gzip');const w=cs.writable.getWriter();w.write(new TextEncoder().encode(str));w.close();const bytes=new Uint8Array(await new Response(cs.readable).arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode.apply(null,bytes.subarray(i,i+0x8000));return btoa(bin);},
async take(tag){const j=this.jobs[tag];if(!j)return 'no job '+tag;const info={tag,state:j.state,progress:j.progress,total:j.total,errors:j.errs,error:j.error,seconds:Math.round((Date.now()-j.started)/1000)};if(j.state!=='done')return info;j.b64=j.b64||await this.gz(JSON.stringify(j.data));return {...info,bytes:j.b64.length,parts:Math.ceil(j.b64.length/this.CH)};},
part(tag,i){const j=this.jobs[tag];const n=Math.ceil(j.b64.length/this.CH);let s='PWPART|'+tag+'|'+i+'|'+n+'|'+j.b64.slice(i*this.CH,(i+1)*this.CH)+'|PWEND';if(s.length<110000)s+='~'.repeat(110000-s.length);return s;},
pageJob(tag,list,delay=1300){return this.start(tag,async job=>{job.total=list.length;job.errs=0;const out=[];let bad=0;for(const [id,path] of list){const t=Date.now();let rec;try{rec={id,url:'https://www.pricecharting.com/game/'+path,...this.parseCard(await this.get('/game/'+path)),fetchedAt:new Date().toISOString()};}catch(e){rec={id,error:String(e)};}if(rec.status!==200){job.errs++;bad++;}else bad=0;out.push(rec);job.progress++;if(bad>=4){job.error='stopped after 4 consecutive failures (last status '+rec.status+')';break;}const wait=delay-(Date.now()-t);if(wait>0)await this.sleep(wait);}return out;});},
decodeQueue(g){const out=[];for(const [k,v] of Object.entries(g)){const [con,set]=k.split('|');for(const e of v){let path,n;if(e.includes('~')){const i=e.lastIndexOf('~');n=e.slice(i+1);path=con+'/'+e.slice(0,i)+'-'+n.toLowerCase();}else{const i=e.lastIndexOf('@');n=e.slice(i+1);path=con+'/'+e.slice(0,i);}out.push([set+'-'+n,path]);}}return out;},
// Queue persists in localStorage so a closed pane can resume. Chunks run in order; finished chunks wait in memory for retrieval.
saveQueue(name,list){localStorage.setItem('pwq_'+name,JSON.stringify(list));return list.length;},
loadQueue(name){return JSON.parse(localStorage.getItem('pwq_'+name)||'[]');},
async chain(name,size=75,delay=1300){this.claimed=this.claimed||new Set();this.chainState={name,running:true};for(;;){const q=this.loadQueue(name).filter(([id])=>!this.claimed.has(id));if(!q.length)break;const chunk=q.slice(0,size),tag=name+'-'+String(Date.now()).slice(-7);chunk.forEach(([id])=>this.claimed.add(id));this.pageJob(tag,chunk,delay);this.jobs[tag].ids=chunk.map(c=>c[0]);await this.jobs[tag].promise;const j=this.jobs[tag];(j.data||[]).filter(r=>r.status!==200).forEach(r=>this.claimed.delete(r.id));if(j.error){this.chainState.error=tag+': '+j.error;break;}while(Object.values(this.jobs).filter(x=>x.state==='done'&&!x.retrieved).length>=3)await this.sleep(3000);}this.chainState.running=false;},
markDone(tag){const j=this.jobs[tag];if(!j)return 'no job';j.retrieved=true;const ok=new Set((j.data||[]).filter(r=>r.status===200).map(r=>r.id));for(const k of Object.keys(localStorage).filter(k=>k.startsWith('pwq_')))this.saveQueue(k.slice(4),this.loadQueue(k.slice(4)).filter(([id])=>!ok.has(id)));j.data=null;j.b64=null;return this.status();},
status(){return {chain:this.chainState,queue:Object.keys(localStorage).filter(k=>k.startsWith('pwq_')).map(k=>[k,this.loadQueue(k.slice(4)).length]),jobs:Object.values(this.jobs).map(j=>[j.tag,j.state,j.progress,j.total,j.errs,j.error,!!j.retrieved])};}
};
'pw v'+__pw.v
