CREATE TABLE IF NOT EXISTS watchlist (user_id TEXT NOT NULL, card_id TEXT NOT NULL, grade TEXT NOT NULL, target REAL, created_at TEXT NOT NULL, PRIMARY KEY (user_id,card_id,grade));
CREATE TABLE IF NOT EXISTS market_cache (card_id TEXT PRIMARY KEY NOT NULL, payload TEXT NOT NULL, fetched_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS collection (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL, card_id TEXT NOT NULL, grade TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 1, purchase_price REAL, purchase_date TEXT, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS collection_user ON collection (user_id, card_id);
CREATE TABLE IF NOT EXISTS alert_settings (user_id TEXT PRIMARY KEY NOT NULL, payload TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS alerts (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL, card_id TEXT NOT NULL, grade TEXT NOT NULL, listing_id TEXT NOT NULL, title TEXT NOT NULL, price REAL NOT NULL, shipping REAL, total REAL NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', url TEXT NOT NULL, image TEXT, buying_option TEXT, limit_price REAL NOT NULL, limit_source TEXT, market_price REAL, seller TEXT, listed_at TEXT, found_at TEXT NOT NULL, seen INTEGER NOT NULL DEFAULT 0, dismissed INTEGER NOT NULL DEFAULT 0, UNIQUE (user_id, listing_id, card_id, grade));
CREATE INDEX IF NOT EXISTS alerts_user ON alerts (user_id, dismissed, found_at);
CREATE TABLE IF NOT EXISTS alert_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, checked INTEGER NOT NULL DEFAULT 0, found INTEGER NOT NULL DEFAULT 0, error TEXT);
-- Investment research (append-only). Rows are never updated or deleted: a correction is a new row
-- with a different content hash. available_at is when this app first had the value; it is never
-- backdated to the event date.
CREATE TABLE IF NOT EXISTS market_observations (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id TEXT NOT NULL, captured_at TEXT NOT NULL, available_at TEXT, source TEXT, source_url TEXT, product_id TEXT, parser_version TEXT NOT NULL, completeness TEXT, sales INTEGER NOT NULL DEFAULT 0, content_hash TEXT NOT NULL, recorded_at TEXT NOT NULL, UNIQUE (card_id, content_hash));
CREATE TABLE IF NOT EXISTS sales_observations (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id TEXT NOT NULL, printing TEXT, language TEXT NOT NULL DEFAULT 'en', grade TEXT NOT NULL, grader TEXT, condition TEXT, event_at TEXT NOT NULL, available_at TEXT, captured_at TEXT NOT NULL, listing_id TEXT NOT NULL, marketplace TEXT, currency TEXT NOT NULL DEFAULT 'USD', price REAL NOT NULL, price_basis TEXT NOT NULL, source_url TEXT, parser_version TEXT NOT NULL, completeness TEXT, content_hash TEXT NOT NULL, recorded_at TEXT NOT NULL, UNIQUE (card_id, grade, listing_id, content_hash));
CREATE INDEX IF NOT EXISTS sales_observations_card ON sales_observations (card_id, grade, event_at);
CREATE TABLE IF NOT EXISTS guide_observations (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id TEXT NOT NULL, guide TEXT NOT NULL, period TEXT NOT NULL, price REAL NOT NULL, price_basis TEXT NOT NULL, event_at TEXT NOT NULL, available_at TEXT, captured_at TEXT NOT NULL, source_url TEXT, parser_version TEXT NOT NULL, content_hash TEXT NOT NULL, recorded_at TEXT NOT NULL, UNIQUE (card_id, guide, period, content_hash));
CREATE TABLE IF NOT EXISTS population_observations (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id TEXT NOT NULL, grader TEXT NOT NULL, counts TEXT NOT NULL, captured_at TEXT NOT NULL, available_at TEXT, source_url TEXT, parser_version TEXT NOT NULL, content_hash TEXT NOT NULL, recorded_at TEXT NOT NULL, UNIQUE (card_id, grader, content_hash));
CREATE TABLE IF NOT EXISTS model_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, model_version TEXT NOT NULL, kind TEXT NOT NULL, mode TEXT NOT NULL, as_of TEXT NOT NULL, dataset_revision TEXT, artifact_hash TEXT, cost_profile TEXT, horizon_months INTEGER, summary TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS score_observations (id INTEGER PRIMARY KEY AUTOINCREMENT, model_version TEXT NOT NULL, as_of TEXT NOT NULL, card_id TEXT NOT NULL, grade TEXT NOT NULL, legacy_score INTEGER, research_rank INTEGER, evidence_status TEXT NOT NULL, payload TEXT NOT NULL, recorded_at TEXT NOT NULL, UNIQUE (model_version, as_of, card_id, grade));
